name: First Workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-24.04

    steps:
      - name: Mostrar información del contexto
        run: |
          echo "Hola a todos"
          echo "Repository owner: ${{ github.repository_owner }}"
          echo "Repository owner ID: ${{ github.repository_owner_id }}"
          echo "Repository ID: ${{ github.repository_id }}"

      - name: Deploy a EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Conectado al servidor EC2"
            cd /var/www/hello-deploy
            git pull origin main