name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Instalar Ruff
        run: |
          pip install ruff

      - name: Dar permisos de ejecución a manage.py
        run: |
          chmod +x manage.py

      - name: Revisar código con Ruff
        run: |
          ruff check .
          ruff format --check .
